### ISSUE TITLE
Bootstrap Button Dropdown Menu is Being Cutoff

### ISSUE THREAD

**Issue by ghost** [Gillardo/bootstrap-ui-treeview#1]
When adding a bootstrap dropdown menu item to each node in the tree using the item-ng-include attribute, it appears the menu cannot extend beyond the boundary of the node's containing parent.  It appears the overflow: hidden attribute of bootstrap's .collapse class is to blame.

**Comment by Gillardo** [comment]
Wow, would never of thought of doing anything like that.  Can you mock up a sample plunkr so i can see and maybe help?  Although it sounds like this is not a bug with the treeview, although i will look if you can set up something

**Comment by ghost** [comment]
Here's a sample: http://plnkr.co/edit/i4prSD?p=preview

You'll notice it works for the top-level containers, but it doesn't work once you start to drill down.  If you have many children and the menu isn't too big, there isn't an issue.  But the last item is always a no-go.

I agree this isn't necessarily an issue with the tree-view plugin itself, it's perhaps an incompatibility between bootstrap, the tree-view, and what I'm trying to accomplish.  I just figured you might have some insight on how to get this work.  I've tried augmenting boostrap's .collapse class, but I can't seem to do so without breaking the plugin.

Any thoughts would be greatly appreciated.

**Comment by ghost** [comment]
Actually, I believe this will work; instead of overriding the .collapse class itself, the .collapse.in class can overwritten in tree-view.css; I believe this will prevent overflow from collapsed nodes being visible while allowing overflow to be visible in expanded nodes?

.tree-view.collapse.in {
  overflow: visible;
}

**Comment by Gillardo** [comment]
Beat me to it. Glad its all working for you now.  Can you close when your
happy.  Thanks

**Comment by Gillardo** [comment]
I have added your css class and a thanks to the readme file.
